spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:59161:xe
    username: 
    password: 
    driver-class-name: oracle.jdbc.driver.OracleDriver

  mail:
    host: smtp.gmail.com
    port: 587
    username: 
    password: 
    properties:
      mail:
        smtp:
          auth: true
          starttls: # 추가 안하면 SMTPSendFailedException
            enalble: true
            required: true

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.Oracle10gDialect

  messages:
    basename: messages,errors

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    view-names: th/*
    cache: false

logging:
  level:
    org.hibernate.SQL: debug

  config: classpath:logback-spring.xml
  charset:
    console: utf-8
  pattern: '%d{yyyy:MM:dd HH:mm:ss.SSS} %-5level --- [%thread] %logger{35} : %msg %n'

server:
  servlet:
    session:
      tracking-modes: cookie
      timeout: 1800

mybatis:
  mapper-locations: /mappings/mapper/*.xml
