--------------------------------------------------------
--  File created - Wednesday-July-07-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MEMBER
--------------------------------------------------------

  CREATE TABLE "BITCAMP"."MEMBER" 
   (	"UUID" NUMBER, 
	"ID" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE), 
	"NAME" VARCHAR2(60 BYTE), 
	"AGE" NUMBER, 
	"PHONE" VARCHAR2(13 BYTE), 
	"ADDRESS" VARCHAR2(200 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"AVAILABLE" VARCHAR2(3 BYTE) DEFAULT 'IN', 
	"LICENSE" VARCHAR2(30 BYTE), 
	"SIGNUP_DATE" TIMESTAMP (6) DEFAULT sysdate, 
	"SIGNOUT_DATE" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "BITCAMP"."MEMBER"."UUID" IS '아이디 인덱스';
REM INSERTING into BITCAMP.MEMBER
SET DEFINE OFF;
Insert into BITCAMP.MEMBER (UUID,ID,PASSWORD,NAME,AGE,PHONE,ADDRESS,EMAIL,AVAILABLE,LICENSE,SIGNUP_DATE,SIGNOUT_DATE) values (41,'abcd','1234','asdfasdf',20,'01021312312','erqewrqwerqwereqwr','email@email.com','IN',null,to_timestamp('2021/07/06 23:10:05.777080000','RRRR/MM/DD HH24:MI:SSXFF'),null);
Insert into BITCAMP.MEMBER (UUID,ID,PASSWORD,NAME,AGE,PHONE,ADDRESS,EMAIL,AVAILABLE,LICENSE,SIGNUP_DATE,SIGNOUT_DATE) values (27,'zcxv','1234','yyyy',22,'01012345678','서울시 강동구 포동포동','panda3@naver.com','IN',null,to_timestamp('2021/06/27 18:33:45.000000000','RRRR/MM/DD HH24:MI:SSXFF'),null);
Insert into BITCAMP.MEMBER (UUID,ID,PASSWORD,NAME,AGE,PHONE,ADDRESS,EMAIL,AVAILABLE,LICENSE,SIGNUP_DATE,SIGNOUT_DATE) values (36,'min1','1234','zxcv',32,'01010101011','서울시 용산구 이태원동','panda7@naver.com','IN',null,to_timestamp('2021/07/01 16:07:39.591275000','RRRR/MM/DD HH24:MI:SSXFF'),null);
Insert into BITCAMP.MEMBER (UUID,ID,PASSWORD,NAME,AGE,PHONE,ADDRESS,EMAIL,AVAILABLE,LICENSE,SIGNUP_DATE,SIGNOUT_DATE) values (32,'zxcv','1234','야호',21,'01033392232','서울시 서대문구 홍제동','panda2@naver.com','IN',null,to_timestamp('2021/06/28 23:23:38.421311000','RRRR/MM/DD HH24:MI:SSXFF'),null);
Insert into BITCAMP.MEMBER (UUID,ID,PASSWORD,NAME,AGE,PHONE,ADDRESS,EMAIL,AVAILABLE,LICENSE,SIGNUP_DATE,SIGNOUT_DATE) values (2,'yaho','1234','userA',14,null,null,null,'IN',null,to_timestamp('2021/06/27 23:24:39.918679000','RRRR/MM/DD HH24:MI:SSXFF'),to_timestamp('1999/12/31 23:59:59.146000000','RRRR/MM/DD HH24:MI:SSXFF'));
Insert into BITCAMP.MEMBER (UUID,ID,PASSWORD,NAME,AGE,PHONE,ADDRESS,EMAIL,AVAILABLE,LICENSE,SIGNUP_DATE,SIGNOUT_DATE) values (26,'zxcv2','1234','sadfdsaf',15,'01020201032','서울시 강남구 반포동','panda@naver.com','OUT','15115151',to_timestamp('2021/06/28 03:25:10.010516000','RRRR/MM/DD HH24:MI:SSXFF'),to_timestamp('2021/07/07 16:53:11.629333000','RRRR/MM/DD HH24:MI:SSXFF'));
Insert into BITCAMP.MEMBER (UUID,ID,PASSWORD,NAME,AGE,PHONE,ADDRESS,EMAIL,AVAILABLE,LICENSE,SIGNUP_DATE,SIGNOUT_DATE) values (34,'zxcv1','1234','afdf',32,'01020314023','서울시 서대문구 연희동','panda4@naver.com','IN',null,to_timestamp('2021/06/29 00:15:50.128289000','RRRR/MM/DD HH24:MI:SSXFF'),null);
Insert into BITCAMP.MEMBER (UUID,ID,PASSWORD,NAME,AGE,PHONE,ADDRESS,EMAIL,AVAILABLE,LICENSE,SIGNUP_DATE,SIGNOUT_DATE) values (35,'idid','1234','yahz',20,'01023421234','서울시 광진구 화양동','panda5@naver.com','IN',null,to_timestamp('2021/06/29 14:35:38.830234000','RRRR/MM/DD HH24:MI:SSXFF'),null);
Insert into BITCAMP.MEMBER (UUID,ID,PASSWORD,NAME,AGE,PHONE,ADDRESS,EMAIL,AVAILABLE,LICENSE,SIGNUP_DATE,SIGNOUT_DATE) values (37,'min9','1919','yaho',22,'01010101011','서울시 용산구 한남동','panda6@naver.com','IN',null,to_timestamp('2021/07/01 16:12:30.637051000','RRRR/MM/DD HH24:MI:SSXFF'),null);
Insert into BITCAMP.MEMBER (UUID,ID,PASSWORD,NAME,AGE,PHONE,ADDRESS,EMAIL,AVAILABLE,LICENSE,SIGNUP_DATE,SIGNOUT_DATE) values (38,'asdf','1234','dkdkdk',19,'01022314123','서울시 서대문구 연희동','panda1@naver.com','IN',null,to_timestamp('2021/07/02 10:02:11.941769000','RRRR/MM/DD HH24:MI:SSXFF'),null);
Insert into BITCAMP.MEMBER (UUID,ID,PASSWORD,NAME,AGE,PHONE,ADDRESS,EMAIL,AVAILABLE,LICENSE,SIGNUP_DATE,SIGNOUT_DATE) values (39,'sads','44565','fdhdgh',12,'01055675756','서울시 마포구 연남동','panda8@naver.com','IN',null,to_timestamp('2021/07/02 10:14:15.544679000','RRRR/MM/DD HH24:MI:SSXFF'),null);
Insert into BITCAMP.MEMBER (UUID,ID,PASSWORD,NAME,AGE,PHONE,ADDRESS,EMAIL,AVAILABLE,LICENSE,SIGNUP_DATE,SIGNOUT_DATE) values (40,'dsfsfdsf','zcxvxczv','dfkfkda',31,'01010313013','서울시 마포구 합정동','panda9@naver.com','IN',null,to_timestamp('2021/07/05 19:16:48.118041000','RRRR/MM/DD HH24:MI:SSXFF'),null);
--------------------------------------------------------
--  DDL for Index MEMBER_UNIQUE
--------------------------------------------------------

  CREATE UNIQUE INDEX "BITCAMP"."MEMBER_UNIQUE" ON "BITCAMP"."MEMBER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index MEMBER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BITCAMP"."MEMBER_PK" ON "BITCAMP"."MEMBER" ("UUID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger MEMBER_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BITCAMP"."MEMBER_TRG" 
BEFORE INSERT ON MEMBER 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "BITCAMP"."MEMBER_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger MEMBER_TRG1
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BITCAMP"."MEMBER_TRG1" 
BEFORE INSERT ON MEMBER 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.UUID IS NULL THEN
      SELECT MEMBER_UUID_SEQ.NEXTVAL INTO :NEW.UUID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "BITCAMP"."MEMBER_TRG1" ENABLE;
--------------------------------------------------------
--  Constraints for Table MEMBER
--------------------------------------------------------

  ALTER TABLE "BITCAMP"."MEMBER" MODIFY ("UUID" NOT NULL ENABLE);
  ALTER TABLE "BITCAMP"."MEMBER" ADD CONSTRAINT "MEMBER_ADDRESS_CHK" CHECK (REGEXP_LIKE(ADDRESS, '^[가-힣a-zA-Z ]{10,50}$')) ENABLE;
  ALTER TABLE "BITCAMP"."MEMBER" ADD CONSTRAINT "MEMBER_NAME_CHK" CHECK (REGEXP_LIKE(NAME, '^[가-힣a-zA-Z]{2,20}$')) ENABLE;
  ALTER TABLE "BITCAMP"."MEMBER" ADD CONSTRAINT "MEMBER_EMAIL_CHK" CHECK (REGEXP_LIKE(EMAIL, '^[0-9a-zA-Z]([-_.]?[0-9a-zA-Z])*@[0-9a-zA-Z]([-_.]?[0-9a-zA-Z])*.[a-zA-Z]{2,3}$')) ENABLE;
  ALTER TABLE "BITCAMP"."MEMBER" ADD CONSTRAINT "MEMBER_ID_CHK" CHECK (REGEXP_LIKE(ID, '^[a-zA-Z0-9]{4,20}$')) ENABLE;
  ALTER TABLE "BITCAMP"."MEMBER" ADD CONSTRAINT "MEMBER_PASSWORD_CHK" CHECK (REGEXP_LIKE(PASSWORD, '^[a-zA-Z0-9]{4,20}$')) ENABLE;
  ALTER TABLE "BITCAMP"."MEMBER" ADD CONSTRAINT "MEMBER_PHONE_CHK" CHECK (REGEXP_LIKE(PHONE, '^010\d{8}$')) ENABLE;
  ALTER TABLE "BITCAMP"."MEMBER" ADD CONSTRAINT "MEMBER_AVAILABLE_CHK" CHECK (available in ('IN', 'OUT')) ENABLE;
  ALTER TABLE "BITCAMP"."MEMBER" MODIFY ("SIGNUP_DATE" NOT NULL ENABLE);
  ALTER TABLE "BITCAMP"."MEMBER" ADD CONSTRAINT "MEMBER_PK" PRIMARY KEY ("UUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "BITCAMP"."MEMBER" MODIFY ("AVAILABLE" NOT NULL ENABLE);
  ALTER TABLE "BITCAMP"."MEMBER" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "BITCAMP"."MEMBER" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "BITCAMP"."MEMBER" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "BITCAMP"."MEMBER" ADD CONSTRAINT "MEMBER_UNIQUE" UNIQUE ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
